version: "3.5"

services:
  backend:
    container_name: poc-med-search
    image: poc-med-search:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PROXY=${DOCKER_PROXY}
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - ${DOCKER_EXPOSE_PORT}:5000
    restart: always
